#!/usr/bin/env python

import csv
import sys


if __name__ == '__main__':
    chosen_book = sys.argv[1]
    current_chapter = None
    rows = list(csv.DictReader(sys.stdin))
    rows.reverse()
    for row in rows:
        if chosen_book == row['Book Title']:
            if current_chapter != row['Chapter Title']:
                if current_chapter is None:
                    print("# Highlights\n")
                current_chapter = row['Chapter Title']
                print(f"## {current_chapter}\n")
            print(row['Highlight'] + "\n")
            print("---\n")
